### ISSUE TITLE
Roadmap 0.8.0

### ISSUE THREAD

**Issue by taylorhakes** [taylorhakes/painless#10]
- [x] Create custom spec reporter. Specified by `-r=spec`
- [x] Create custom dot reporter. Now the default reporter.
- [x] Removed dependency on tap-spec
- [x] Make easy to use reporter API
- [x] Document new reporter API
- [x] Changed tap output from `-t` to `-r=tap`
- [x] Show total number of tests passed and failed
- [x] Show total execution time
- [x] Show individual times on spec reporter and tap reporter
- [x] Expose `chai.use` to allow more customization
- [x] Improve diffs for users without color console
- [x] Update readme with new reporters
- [x] Support including additonal files via `-i,--include`
- [x] Allow custom reports to be used in `-r,--reporter`

Future
- Show slow tests
- Bail early on first failed test
- Allow names for test groups

Most of the features in https://github.com/taylorhakes/painless/issues/9

**Comment by af** [comment]
This is awesome! :+1:  

Another idea for the future: allow non-core reporters to be specified with `-r`. Painless could `require()` the given reporter name if it isn't one of the ones in core. This would be an easy way to let people work on more reporters without them needing to be a part of the main repo.

**Comment by taylorhakes** [comment]
Read my mind! I was going to add that.

**Comment by taylorhakes** [comment]
0.8.0 is out on github and NPM. [Here is a link.](https://github.com/taylorhakes/painless/releases/tag/0.8.0)

New reporter API is described in the docs. I made it really easy to create a custom reporter.
https://github.com/taylorhakes/painless/blob/master/DOCUMENTATION.md#reporter-api

@af Thanks for all of the suggestions. If you have other ideas, please create more tickets.

**Comment by af** [comment]
Careful what you wish for ;)

Looking forward to trying out 0.8 tonight!
